VIA_ENABLE = yes
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_software

MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = yes

TD_LSFT_CAPSLOCK_ENABLE = yes
STARTUP_NUMLOCK_ON = yes
ENCODER_DEFAULTACTIONS_ENABLE = yes
INVERT_NUMLOCK_INDICATOR = yes

ALTTAB_SCROLL_ENABLE = yes
